#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

# Color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Print usage helper
usage() {
    echo "Usage: $0 <platform> [mode]"
    echo "Platforms: web, windows, linux, android"
    echo "Modes:     release (default), debug"
    echo "Example:   $0 linux"
    echo "           $0 android debug"
    exit 1
}

# Ensure at least one argument is provided
if [ $# -lt 1 ]; then
    usage
fi

PLATFORM=$(echo "$1" | tr '[:upper:]' '[:lower:]')
MODE=${2:-release}
MODE=$(echo "$MODE" | tr '[:upper:]' '[:lower:]')

# Validate platform
case "$PLATFORM" in
    web|windows|linux|android) ;;
    *)
        log_error "Invalid platform '$PLATFORM'"
        usage
        ;;
esac

# Validate mode
case "$MODE" in
    release|debug) ;;
    *)
        log_error "Invalid mode '$MODE'"
        usage
        ;;
esac

log_info "Collecting git metadata..."

# Default fallback values
GIT_HASH="unknown"
GIT_DIRTY="true"
GIT_TAG="v1.0.0"

# Check if git is installed and we are in a git repository
if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    # Get short commit hash
    if git rev-parse --short HEAD >/dev/null 2>&1; then
        GIT_HASH=$(git rev-parse --short HEAD)
    else
        log_warn "No commits in git repository yet."
        GIT_HASH="no-commit"
    fi

    # Check for uncommitted changes
    if [ -n "$(git status --porcelain)" ]; then
        GIT_DIRTY="true"
    else
        GIT_DIRTY="false"
    fi

    # Get exact tag on current commit if available
    CURRENT_TAG=$(git tag --points-at HEAD 2>/dev/null | head -n 1 || true)
    if [ -n "$CURRENT_TAG" ]; then
        GIT_TAG="$CURRENT_TAG"
    else
        # No exact tag, check if any tag exists to use as fallback or describe
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
        if [ -n "$LATEST_TAG" ]; then
            GIT_TAG="$LATEST_TAG"
        else
            GIT_TAG="v1.0.0"
        fi
    fi
else
    log_warn "Not a git repository or git command not found. Using safe fallbacks."
fi

# Validation warnings for release builds
if [ "$MODE" = "release" ]; then
    if [ "$GIT_DIRTY" = "true" ]; then
        log_warn "Building a RELEASE version with uncommitted/dirty changes!"
    fi
    # Check if tag is semver-compliant (e.g., v1.2.3)
    if [[ ! "$GIT_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?$ ]]; then
        log_warn "Git tag '$GIT_TAG' does not follow SemVer format (e.g. v1.0.0). It will be treated as dirty."
    fi
fi

log_info "Detected Git Settings:"
echo "  Commit Hash: $GIT_HASH"
echo "  Dirty Files: $GIT_DIRTY"
echo "  Git Tag:     $GIT_TAG"

# Generate version.dart using printf to avoid using cat inside bash
VERSION_FILE="lib/versioning/version.dart"
log_info "Generating $VERSION_FILE..."

printf "// Auto-generated by build.sh. Do not commit or modify manually.\n" > "$VERSION_FILE"
printf "const String kGitCommitHash = '%s';\n" "$GIT_HASH" >> "$VERSION_FILE"
printf "const bool kGitDirty = %s;\n" "$GIT_DIRTY" >> "$VERSION_FILE"
printf "const String kGitTag = '%s';\n" "$GIT_TAG" >> "$VERSION_FILE"

log_success "Generated version.dart successfully."

# Flutter Build Execution
FLUTTER_MODE="--release"
if [ "$MODE" = "debug" ]; then
    FLUTTER_MODE="--debug"
fi

log_info "Building Mima for $PLATFORM ($MODE)..."

# Run the appropriate flutter build command
flutter build "$PLATFORM" $FLUTTER_MODE

log_success "Build completed successfully for $PLATFORM ($MODE)!"
